export {
  CONCAT_TYPE,
  concat,
  DEFAULT_VALUE_TYPE,
  defaultValue,
  type DefaultValueResult,
  EXTRACT_FROM_HTML_TYPE,
  extractFromHtml,
  type ExtractFromHtmlResult,
  FIND_ALL_TYPE,
  FIND_TYPE,
  find,
  findAll,
  type FindAllResult,
  type FindResult,
  HTML_TO_MARKDOWN_TYPE,
  htmlToMarkdown,
  type HtmlToMarkdownResult,
  JSON_TO_TABLE_TYPE,
  jsonToAsciiTable,
  type JsonToTableResult,
  MARKDOWN_TO_HTML_TYPE,
  markdownToHtml,
  type MarkdownToHtmlResult,
  REPLACE_TYPE,
  replace,
  type ReplaceResult,
  SLUGIFY_TYPE,
  slugify,
  type SlugifyResult,
  SPLIT_TYPE,
  split,
  type SplitResult,
  STRIP_HTML_TYPE,
  stripHtml,
  type StripHtmlResult,
} from './text';

import {
  concat,
  defaultValue,
  extractFromHtml,
  find,
  findAll,
  htmlToMarkdown,
  jsonToAsciiTable,
  markdownToHtml,
  replace,
  slugify,
  split,
  stripHtml,
} from './text';

/** Every Text action, for catalog builds and registration. */
export const textActions = [
  concat,
  replace,
  split,
  find,
  findAll,
  slugify,
  defaultValue,
  stripHtml,
  jsonToAsciiTable,
  markdownToHtml,
  htmlToMarkdown,
  extractFromHtml,
] as const;
